name: quickbuild-android

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quickandroid:
      runs-on: ubuntu-latest
      env:
        VMAJOR: 135
        VERSION: 135.0.7049.111
        SRCDIR: chromium-src
      steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: "remove not needed items"
        run: |
          sudo rm -rf /usr/local/.ghcup \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/local/share/powershell \
            /usr/local/lib/android \
            /opt/ghc \
            /opt/hostedtoolcache/CodeQL \
            /imagegeneration \
            "$AGENT_TOOLSDIRECTORY"
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: android-src-${{ env.VERSION }}
          path: /home/runner/work/gollum/gollum/chromium-src
          github-token: ${{ secrets.PAT }}
          run-id: 14606924225

      - name: Download out directory
        uses: actions/download-artifact@v4
        with:
          name: chromium-out-${{ env.VERSION }}
          path: /home/runner/work/gollum/gollum/chromium-src
          github-token: ${{ secrets.PAT }}
          run-id: 14606924225

      - name: Download versioned branding patches
        uses: actions/download-artifact@v4
        with:
          name: android-patch-${{ env.VERSION }}
          path: /home/runner/work/gollum/gollum/chromium-src
          github-token: ${{ secrets.PAT }}
          run-id: 14606924225

      - uses: actions/checkout@v4
        with:
          repository: 'COD3HUNT3R/android'
          path: 'chromium-src/android'
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        with:
          repository: 'COD3HUNT3R/patches'
          path: 'chromium-src/patches'
          token: ${{ secrets.PAT }}

      - name: Clone depot_tools
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          cd $SRCDIR
          echo "Clone depot_tools..."
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools
          echo "::add-path::$GITHUB_WORKSPACE/chromium-src/depot_tools"
          sudo apt install -y ninja-build gperf

      - name: Extract tar
        shell: bash
        run: |
          cd $SRCDIR && ls -lsh
          tar -xf chromium-$VERSION.tar.xz
          tar -xf out.tar.zst
          ls -lsh
          rm -f chromium-$VERSION.tar.xz out.tar.zst
          mv out chromium-$VERSION && cd chromium-$VERSION
          patch -p1 < ../baraqah$VMAJOR-$VERSION-branding.patch
          patch -p1 < ../patches/$VMAJOR/common/baraqah$VMAJOR-banned-tld.patch
          patch -p1 < ../patches/$VMAJOR/common/baraqah$VMAJOR-baraqah-dns.patch
          patch -p1 < ../patches/$VMAJOR/android/baraqah$VMAJOR-news-feeds.patch
          rm -rf chrome/android/java/res_chromium_base
          cp -r ../android/chrome .
          pwd && ls -lsh chrome/android/java/res_chromium_base

      - name: Build apk
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          ninja -j 4 -C out/release chrome_public_apk
          ls -lsh out/release/apks

      - name: Upload apks
        uses: actions/upload-artifact@v4
        with:
          name: apks-${{ env.VERSION }}
          path: /home/runner/work/gollum/gollum/chromium-src/chromium-${{ env.VERSION }}/out/release/apks

      - name: Compress artifacts
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          ZSTD_CLEVEL=12 tar -I zstd -cvpf /home/runner/work/gollum/gollum/chromium-src/out.tar.zst ./out

      - name: Upload out directory
        uses: actions/upload-artifact@v4
        with:
          name: chromium-out-${{ env.VERSION }}
          path: /home/runner/work/gollum/gollum/chromium-src/out.tar.zst
          overwrite: true
